"""3D polycrystal generator via Voronoi tessellation.

Supports FCC, BCC, and HCP crystal structures (the three lattice families
covered by Wagih et al., Nat. Commun. 2020). Writes a LAMMPS data file
compatible with the equilibration decks under
`project/data/examples/nc_swap_CuNi/` (single atom type; solute is introduced
later via LAMMPS `set type/fraction`). Replaces the advisor's 2D columnar
`create_nanocrystal.py` for the 3D Wagih-style pipeline.

Usage as module:
    from generate_polycrystal import build_polycrystal, write_lammps_data
    pos, box = build_polycrystal(
        box=100.0, n_grains=8, structure="fcc", lattice_a=4.05, structure_seed=1
    )
    write_lammps_data("poly.lmp", pos, box, n_atom_types=2, header="Al polycrystal")

Usage as CLI:
    python generate_polycrystal.py --structure fcc --box 100 --grains 8 \
        --lattice-a 4.05 --structure-seed 1 --out poly.lmp
    python generate_polycrystal.py --structure bcc --box 100 --grains 8 \
        --lattice-a 2.866 --out fe_poly.lmp                 # alpha-Fe
    python generate_polycrystal.py --structure hcp --box 100 --grains 8 \
        --lattice-a 3.209 --c-over-a 1.623 --out mg_poly.lmp  # Mg

Note on RNG seeds: `structure_seed` controls only the polycrystal geometry
(grain centers + grain orientations). Downstream LAMMPS steps have their own,
independent seeds — solute placement (`set type/fraction ... solute_seed`),
HMC swaps (`fix atom/swap ... swap_seed`), and initial velocities
(`velocity create ... velocity_seed`). Keep them named distinctly so ensemble
scans over any one dimension don't collide.

Algorithm:
    1. Random grain centers in a cubic periodic box.
    2. Random 3D orientation per grain (uniform SO(3) via scipy.Rotation.random).
    3. For each grain, replicate the crystal template (FCC / BCC / HCP) to cover
       the box diagonal plus padding, rotate, translate to the grain center, and
       keep atoms that (a) fall inside the box without PBC wrap and
       (b) have this grain as nearest center under PBC.
    4. Remove close pairs at GBs (distance < `min_dist`, default = half the
       nearest-neighbor distance for the chosen structure).

Why not wrap the template into the box? A template that covers `diag + a` after
rotation is larger than the box along every axis; wrapping it would map multiple
template atoms to the same wrapped position, inflating the density. Instead we
keep only the portion of the rotated template that already lies inside the box,
which guarantees each box position is produced by at most one template image
per grain.
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass

import numpy as np
from scipy.spatial import cKDTree
from scipy.spatial.transform import Rotation


# Structure definitions. `lat_vecs(a, c)` returns the 3×3 matrix whose rows are
# the conventional (for cubic) / primitive (for hcp) lattice vectors, and
# `basis_frac` gives atom positions in fractional coordinates within one cell.
# `nn_dist(a, c)` is the ideal nearest-neighbor distance (used for the default
# close-pair cutoff and for reporting the expected atom count).
_STRUCTURES = {
    "fcc": {
        "lat_vecs": lambda a, c: a * np.eye(3),
        "basis_frac": np.array(
            [[0.0, 0.0, 0.0], [0.5, 0.5, 0.0], [0.5, 0.0, 0.5], [0.0, 0.5, 0.5]]
        ),
        "nn_dist": lambda a, c: a / np.sqrt(2.0),
        "atoms_per_cell": 4,
        "default_c_over_a": None,
    },
    "bcc": {
        "lat_vecs": lambda a, c: a * np.eye(3),
        "basis_frac": np.array([[0.0, 0.0, 0.0], [0.5, 0.5, 0.5]]),
        "nn_dist": lambda a, c: a * np.sqrt(3.0) / 2.0,
        "atoms_per_cell": 2,
        "default_c_over_a": None,
    },
    "hcp": {
        # Primitive hexagonal cell: a1=(a,0,0), a2=(-a/2, a√3/2, 0), a3=(0,0,c).
        "lat_vecs": lambda a, c: np.array(
            [[a, 0.0, 0.0], [-a / 2.0, a * np.sqrt(3.0) / 2.0, 0.0], [0.0, 0.0, c]]
        ),
        "basis_frac": np.array([[0.0, 0.0, 0.0], [1.0 / 3.0, 2.0 / 3.0, 0.5]]),
        # For ideal c/a = sqrt(8/3), all 12 nearest neighbors sit at distance a.
        "nn_dist": lambda a, c: a,
        "atoms_per_cell": 2,
        "default_c_over_a": np.sqrt(8.0 / 3.0),
    },
}


@dataclass
class Box:
    """Orthorhombic periodic box [0, Lx) x [0, Ly) x [0, Lz)."""

    lx: float
    ly: float
    lz: float

    @property
    def lengths(self) -> np.ndarray:
        return np.array([self.lx, self.ly, self.lz])


def _crystal_template(
    structure: str, lattice_a: float, lattice_c: float | None, extent: float
) -> np.ndarray:
    """Positions of a perfect single-crystal block covering a cube of side
    `extent`, centered on the origin.

    The block is generated by replicating the structure's unit cell along its
    lattice vectors. For non-orthogonal HCP cells, the replication range is
    sized from the shortest lattice-vector length so the bounding cube of
    side `extent` is always covered (some atoms outside the cube are also
    produced; they get filtered downstream).
    """
    spec = _STRUCTURES[structure]
    c = lattice_c if lattice_c is not None else (
        lattice_a * spec["default_c_over_a"] if spec["default_c_over_a"] else lattice_a
    )
    lat_vecs = spec["lat_vecs"](lattice_a, c)          # rows = a1, a2, a3
    basis_frac = spec["basis_frac"]                    # (k, 3)

    shortest = float(min(np.linalg.norm(v) for v in lat_vecs))
    n = int(np.ceil(extent / shortest)) + 1
    idx = np.arange(-n, n + 1)
    ix, iy, iz = np.meshgrid(idx, idx, idx, indexing="ij")
    cells = np.stack([ix.ravel(), iy.ravel(), iz.ravel()], axis=1).astype(np.float64)
    # (n_cells, 1, 3) + (1, k, 3) -> (n_cells, k, 3) -> (n_cells*k, 3) @ lat_vecs
    frac = (cells[:, None, :] + basis_frac[None, :, :]).reshape(-1, 3)
    return frac @ lat_vecs


def _build_pbc_grain_tree(
    centers: np.ndarray, box: Box
) -> tuple[cKDTree, np.ndarray]:
    """Build a KDTree over the 27 periodic images of grain centers.

    Returns `(tree, image_to_grain)` so callers can query nearest image and
    map back to the original grain index. Reused across the grain loop
    instead of being rebuilt per grain.
    """
    shifts = np.array(
        [
            [dx * box.lx, dy * box.ly, dz * box.lz]
            for dx in (-1, 0, 1)
            for dy in (-1, 0, 1)
            for dz in (-1, 0, 1)
        ]
    )
    images = (centers[:, None, :] + shifts[None, :, :]).reshape(-1, 3)
    image_to_grain = np.tile(np.arange(len(centers))[:, None], (1, len(shifts))).ravel()
    return cKDTree(images), image_to_grain


def _pbc_min_center_distance(centers: np.ndarray, box: Box) -> float:
    """Smallest pairwise distance between grain centers under PBC."""
    tree, _ = _build_pbc_grain_tree(centers, box)
    # k=2 because the nearest image of a center is itself (distance 0).
    dists, _ = tree.query(centers, k=2)
    return float(dists[:, 1].min())


def _remove_close_pairs(pos: np.ndarray, box: Box, min_dist: float) -> np.ndarray:
    """Remove one atom of every pair closer than `min_dist` under PBC."""
    tree = cKDTree(pos, boxsize=box.lengths)
    pairs = tree.query_pairs(r=min_dist, output_type="ndarray")
    if len(pairs) == 0:
        return pos
    drop = np.zeros(len(pos), dtype=bool)
    for i, j in pairs:
        if drop[i] or drop[j]:
            continue
        drop[j] = True
    return pos[~drop]


def build_polycrystal(
    box: float | tuple[float, float, float],
    n_grains: int,
    structure: str = "fcc",
    lattice_a: float = 4.05,
    lattice_c: float | None = None,
    structure_seed: int = 0,
    min_dist: float | None = None,
    min_grain_separation: float | None = None,
) -> tuple[np.ndarray, Box]:
    """Build a 3D FCC / BCC / HCP polycrystal by Voronoi tessellation.

    Parameters
    ----------
    box : float or (lx, ly, lz)
        Box side length(s) in Å. Scalar => cubic.
    n_grains : int
        Number of grains (Voronoi seeds).
    structure : {"fcc", "bcc", "hcp"}
    lattice_a : float
        In-plane lattice constant in Å.
    lattice_c : float, optional
        Only used for HCP. Defaults to the ideal ratio c = a * sqrt(8/3).
    structure_seed : int
        RNG seed controlling **only the polycrystal geometry** — grain centers
        and grain orientations. Solute placement, HMC swaps, and MD velocities
        use their own independent seeds downstream in LAMMPS.
    min_dist : float, optional
        Close-pair cutoff in Å. Defaults to half the ideal nearest-neighbor
        distance of the chosen structure.
    min_grain_separation : float, optional
        Minimum allowed PBC distance between any two grain centers. Defaults
        to `2 * lattice_a` (just strict enough to reject literal overlaps —
        the expected min center separation in a random Poisson placement is
        `~0.55 * L * n_grains^(-1/3)`, far looser). If violated, raises
        ValueError — re-roll with a different `structure_seed`.

    Returns
    -------
    positions : (N, 3) array
    box : Box
    """
    if structure not in _STRUCTURES:
        raise ValueError(
            f"unknown structure {structure!r}; choose from {sorted(_STRUCTURES)}"
        )
    if np.isscalar(box):
        b = Box(float(box), float(box), float(box))
    else:
        b = Box(*map(float, box))

    spec = _STRUCTURES[structure]
    c = lattice_c if lattice_c is not None else (
        lattice_a * spec["default_c_over_a"] if spec["default_c_over_a"] else lattice_a
    )
    if min_dist is None:
        min_dist = spec["nn_dist"](lattice_a, c) / 2.0

    rng = np.random.default_rng(structure_seed)
    centers = rng.uniform(0.0, 1.0, size=(n_grains, 3)) * b.lengths
    rotations = Rotation.random(num=n_grains, random_state=rng)

    # Reject runs where two grain centers happen to land too close — a
    # degenerate grain would produce almost no atoms and contaminate GB
    # statistics. Re-roll with a different structure_seed if this fires.
    if n_grains >= 2:
        sep_threshold = (
            min_grain_separation
            if min_grain_separation is not None
            else 2.0 * lattice_a
        )
        actual_sep = _pbc_min_center_distance(centers, b)
        if actual_sep < sep_threshold:
            raise ValueError(
                f"min grain-center separation {actual_sep:.2f} Å < "
                f"threshold {sep_threshold:.2f} Å for structure_seed="
                f"{structure_seed}; re-roll with a different seed."
            )

    # Template must cover the box after rotation regardless of orientation —
    # use the box diagonal plus one lattice spacing.
    diag = float(np.linalg.norm(b.lengths))
    template = _crystal_template(structure, lattice_a, c, diag + lattice_a)

    # Build the PBC grain-center tree once and reuse across the grain loop.
    grain_tree, image_to_grain = _build_pbc_grain_tree(centers, b)

    L = b.lengths
    all_pos = []
    for g in range(n_grains):
        rotated = rotations[g].apply(template) + centers[g]
        # Keep atoms that land inside the box (no wrap — wrapping an oversized
        # template duplicates atoms). The template was sized so that at least
        # one box-sized region of the rotated lattice falls inside.
        inside = np.all((rotated >= 0.0) & (rotated < L), axis=1)
        cand = rotated[inside]
        _, img_idx = grain_tree.query(cand, k=1)
        owners = image_to_grain[img_idx]
        all_pos.append(cand[owners == g])
    positions = np.concatenate(all_pos, axis=0)
    positions = _remove_close_pairs(positions, b, min_dist)
    return positions, b


def write_lammps_data(
    path: str,
    positions: np.ndarray,
    box: Box,
    n_atom_types: int = 2,
    atom_type: int = 1,
    header: str = "polycrystal",
) -> None:
    """Write a LAMMPS `atomic` style data file.

    All atoms are assigned `atom_type` (default 1). The second type is
    declared so that downstream `set type/fraction` can introduce the solute
    without modifying the data file.
    """
    n = len(positions)
    with open(path, "w") as f:
        f.write(f"{header}\n\n")
        f.write(f"{n} atoms\n\n")
        f.write(f"{n_atom_types} atom types\n\n")
        f.write(f"0.0 {box.lx:.6f} xlo xhi\n")
        f.write(f"0.0 {box.ly:.6f} ylo yhi\n")
        f.write(f"0.0 {box.lz:.6f} zlo zhi\n\n")
        f.write("Atoms\n\n")
        for i, (x, y, z) in enumerate(positions, start=1):
            f.write(f"{i} {atom_type} {x:.6f} {y:.6f} {z:.6f}\n")


def _expected_density(structure: str, a: float, c: float | None) -> float:
    """Ideal atoms per Å³ for the chosen structure."""
    spec = _STRUCTURES[structure]
    if structure in ("fcc", "bcc"):
        return spec["atoms_per_cell"] / a**3
    if structure == "hcp":
        if c is None:
            c = a * spec["default_c_over_a"]
        cell_volume = a**2 * c * np.sqrt(3.0) / 2.0
        return spec["atoms_per_cell"] / cell_volume
    raise ValueError(structure)


def _cli() -> None:
    p = argparse.ArgumentParser(
        description=__doc__.splitlines()[0],
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--structure",
        choices=sorted(_STRUCTURES),
        default="fcc",
        help="crystal structure",
    )
    p.add_argument("--box", type=float, default=100.0, help="cubic box side [Å]")
    p.add_argument("--grains", type=int, default=8, help="number of grains")
    p.add_argument(
        "--lattice-a", type=float, default=4.05, help="lattice a [Å] (default Al)"
    )
    p.add_argument(
        "--lattice-c",
        type=float,
        default=None,
        help="HCP lattice c [Å]; overrides --c-over-a",
    )
    p.add_argument(
        "--c-over-a",
        type=float,
        default=None,
        help="HCP c/a ratio (default: ideal sqrt(8/3) ≈ 1.633)",
    )
    p.add_argument(
        "--structure-seed",
        type=int,
        default=1,
        help="RNG seed for grain centers + orientations (NOT solute/swap/velocity seeds)",
    )
    p.add_argument("--min-dist", type=float, default=None, help="close-pair cutoff [Å]")
    p.add_argument("--types", type=int, default=2, help="n atom types to declare")
    p.add_argument("--out", type=str, required=True, help="output LAMMPS data file")
    p.add_argument("--header", type=str, default=None)
    args = p.parse_args()

    c = args.lattice_c
    if c is None and args.c_over_a is not None:
        c = args.lattice_a * args.c_over_a

    header = args.header or f"{args.structure.upper()} polycrystal"
    pos, box = build_polycrystal(
        box=args.box,
        n_grains=args.grains,
        structure=args.structure,
        lattice_a=args.lattice_a,
        lattice_c=c,
        structure_seed=args.structure_seed,
        min_dist=args.min_dist,
    )
    write_lammps_data(args.out, pos, box, n_atom_types=args.types, header=header)

    density = _expected_density(args.structure, args.lattice_a, c)
    expected = density * box.lx * box.ly * box.lz
    print(
        f"Wrote {args.out}: {len(pos)} atoms ({args.structure.upper()}) in "
        f"{box.lx:.1f}x{box.ly:.1f}x{box.lz:.1f} Å "
        f"(perfect-lattice would be {expected:.0f}; "
        f"deficit {1 - len(pos)/expected:.1%} from GB close-pair removal)"
    )


if __name__ == "__main__":
    _cli()
