#!/usr/bin/env python3
"""Generate a LAMMPS `include` file defining the static GB-atom group from
the a-CNA GB mask.

The targeted-swap HMC deck (`data/decks/hmc_AlMg_targeted.lammps`) restricts
`fix atom/swap` to groups that exclude the bulk "dead weight". Those groups
are built as unions of:
  - GB_static : every GB lattice site  (this file)
  - Mg_init / Al_init : the initial solute / solvent atoms  (defined in the deck)

Since atoms only vibrate around fixed lattice sites (substitutional model,
no vacancies), GB membership is static for the whole trajectory — so this
include file is generated ONCE from the mask and reused by every targeted run.

Inputs:
  --gb-mask   boolean .npy of length N_total; True = GB site (atom id-1 indexed)
  --out       output LAMMPS include file
  --per-line  atom IDs per `group` line (default 200; keeps line length modest)

Output: an include file of additive `group GB_static id <ids...>` lines.
"""
from __future__ import annotations
import argparse
from pathlib import Path

import numpy as np


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--gb-mask", type=Path, required=True)
    p.add_argument("--out", type=Path, required=True)
    p.add_argument("--per-line", type=int, default=200,
                   help="atom IDs per `group` line (default 200)")
    args = p.parse_args()

    gb_mask = np.load(args.gb_mask).astype(bool)
    n_total = int(gb_mask.size)
    gb_ids = np.where(gb_mask)[0] + 1  # LAMMPS atom IDs are 1-indexed
    n_gb = int(gb_ids.size)
    n_lines = (n_gb + args.per_line - 1) // args.per_line

    out_lines = [
        "# LAMMPS include file: static GB-atom group for targeted-swap HMC.",
        "# GENERATED by scripts/make_gb_group_include.py -- do not edit by hand.",
        f"#   source mask : {args.gb_mask}",
        f"#   N_total     : {n_total}",
        f"#   N_GB        : {n_gb}  (GB_frac = {n_gb / n_total:.4f})",
        "# Defines group `GB_static` via additive `group ... id` lines.",
        "",
    ]
    for i in range(0, n_gb, args.per_line):
        chunk = gb_ids[i:i + args.per_line]
        out_lines.append("group GB_static id " + " ".join(str(int(x)) for x in chunk))
    out_lines.append("")

    args.out.write_text("\n".join(out_lines))
    print(f"wrote {args.out}")
    print(f"  N_total = {n_total}  N_GB = {n_gb}  GB_frac = {n_gb / n_total:.4f}")
    print(f"  {n_lines} `group GB_static id` lines, {args.per_line} IDs/line")


if __name__ == "__main__":
    main()
